server:
  port: 8084

spring:
  datasource:
    druid:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/spring?useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver