server:
  port: 8017
spring:
  boot:
    admin:
      client:
        url: http://localhost:8016/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always